/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	event_num: number;
	stage: {
		slideshow_interval: number;
		schedule_scroll_interval: number;
		[k: string]: unknown;
	};
	music: {
		updateInterval?: number;
		lastfm?: {
			enabled?: boolean;
			apiKey?: string;
			source?: string;
			[k: string]: unknown;
		};
		party?: {
			enabled?: boolean;
			url?: string;
			id?: string;
			[k: string]: unknown;
		};
		[k: string]: unknown;
	};
	network: {
		snmp: {
			enabled: boolean;
			host: string;
			community: string;
			interval: number;
			oids: {
				down: string;
				up: string;
				[k: string]: unknown;
			};
			[k: string]: unknown;
		};
		bwHighThreshold: number;
		[k: string]: unknown;
	};
	schedule: {
		icalAddress?: string;
		debugExtraEvents?: boolean;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
