/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PersonsData {
	person1?: string;
	person1desc?: string;
	person2?: string;
	person2desc?: string;
	person3?: string;
	person3desc?: string;
}
