/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ShoutboxShouts {
	shouts: {
		id: string;
		timestamp: string;
		message: string;
		user: {
			name: string;
			avatar_url: string;
			[k: string]: unknown;
		};
		[k: string]: unknown;
	}[];
	[k: string]: unknown;
}
